import parseFont from './parse-font';

import {
  notice,
  Color,
  parseColor,
  oneOrTwoValues,
  praseString,
  parseStringInt,
  parseStringFloat,
  parseColorString,
  fourValuesShortCut,
  parseStringTransform,
  rectVertices,
  appendUnit,
  sortOrderedSprites,
  generateID,
  sizeToPixel,
} from './utils';

import {
  attr,
  flow,
  absolute,
  inherit,
  inheritAttributes,
  setDeprecation,
  deprecate,
  parseValue,
  relative,
  cachable,
} from './decorators';

import {findColor, cacheContextPool} from '../helpers/render';

export {
  cachable,
  findColor,
  cacheContextPool,
  appendUnit,
  attr,
  Color,
  deprecate,
  flow,
  fourValuesShortCut,
  notice,
  oneOrTwoValues,
  absolute,
  relative,
  inherit,
  inheritAttributes,
  parseColor,
  parseColorString,
  praseString,
  parseStringFloat,
  parseStringInt,
  parseStringTransform,
  parseValue,
  rectVertices,
  setDeprecation,
  sortOrderedSprites,
  generateID,
  sizeToPixel,
  parseFont,
};
